### ISSUE TITLE
Time to unleash onto CPAN!

### ISSUE THREAD

**Issue by mohawk2** [plicease/FFI-Platypus#1]

**Comment by plicease** [comment]
I've rewritten the innards and the interface, mostly from scratch.  Importantly the major performance improvements are still there (checked this with `FFI::Performance`), and several aspects of the build process have been simplified and as a result it should be much easier to maintain.  The original implementation is tagged as v0.01 (unreleased).

Before releasing I'd like to get it to feature parity with `FFI::Raw`.  These are the things that are missing:

 - float, double and (maybe) long double support
 - tests for opaque pointers
 - calling back to Perl from C ("callbacks" or "closures")

This is a "nice to have":

 - custom types or "ffi typemaps"

but it isn't supported by `FFI::Raw` either, so I am tempted to delay implementation.  At least some thought should go into how this is going to work before this goes to CPAN, since that was a major driving force behind platypus.

I think that is all doable in the next month or so.  In addition before releasing I plan on port one or more of these, in order to make sure the interface is sane:

 - `FFI::TinyCC`
 - `FFI::Util` - platypus should make this module largely obsolete, but porting it should improve performance of anything that uses it, even if the caller itself is using `FFI::Raw`.
 - `File::LibMagic::FFI`
 - `UUID::FFI`

**Comment by plicease** [comment]
Type support looks pretty good:
  - int, float and opaque pointer types supported
  - strings are supported, except as a return type from a closure (calling Perl from C)
  - pointers to int, float and opaque pointer types are supported calling C from Perl only
  - fixed length arrays of int, float and opaque pointer types supported calling C from Perl only
  - closure types are supported as arguments calling C from Perl only

Custom type support still needs to be added.  Other types like pointers or arrays of strings can be and should be added later.  Support for arrays and pointer to int, float and opaque pointers for closures can be added later if urgency is found for that feature.

There is something weird going on with signed 64 bit integers on 32 bit Perls (#2).  I can't reproduce the problem with `FFI::Raw`, so it does not appear to be a bug with `Math::Int64`, unless the way I am returning values is exercising a different code path in `Math::Int64`.

I think everything that you can do with `FFI::Raw` can be done with platypus at this point.  Some of the ways you do it may be different, for example I don't provide anything like `FFI::Raw::MemPtr`, instead you must use `free` and `malloc` directly.  I expose an interface to these and other standard C memory functions.  Many FFI devs seem to end up writing their own malloc bindings anyway, for one reason or another.  FFI::Raw supports strings from a closure, but it isn't reentrant, so if you want to return a string in platypus, you return an opaque pointer and use `malloc` / `strdup` or something like that.

Documentation needs to be improved, particularly in regard to types.  I am going to create a `lib/FFI/Platypus/Type.pod` to document the many different ways that you can define and use types, because it is a complicated subject, and likely to get more complicated as we add custom and other types.

I am pretty sure that I can start porting some of the distros mentioned in the previous comment over to `FFI::Platypus`.  I already ported examples from `FFI::Raw`.  They work as well as the `FFI::Raw` versions at this point.  The ones that work in `FFI::Raw` work with platypus and the ones that dump core in `FFI::Raw` dump core also in platypus.  I will probably end up removing the ones that do not work.  I should also write some of my own examples.

**Comment by plicease** [comment]
Added custom types written in Perl.  released a alpha here as 0.06:

https://dist.wdlabs.com/FFI-Platypus-0.06.tar.gz

Also included is a fix for 32 bit Perls (#2).  I've opened a bunch of issues that are still outstanding, not all of them need to be addressed before going to CPAN.  One problem is that the documentation needs to be improved.

The most serious open issue is probably #4, followed by perhaps #13 if peoples care about windows.

It would be nice to address #3 as well, not that I think people should be using Perl 5.8, but for those that must it is a nice win over `FFI::Raw` which requires 5.10.

Tested these platforms via VMs and physical hardware:

  - Linux 64 bit
  - Debian kFreeBSD 64 bit
  - FreeBSD (32, 64 bit)
  - Cygwin (64 bit)
  - MSWin32 (32 bit)
  - NetBSD 64 bit
  - Solaris (64 bit OS, 32 bit compiler, apparently)
  - Mac OS X (64 bit)

This platform failed:

  - OpenBSD ~ problem has to do with libff requiring pthreads and perl isn't threaded.  Had similar problem with `FFI::Raw` which I eventually manage to work around.  Either dig up the solution that I found there, or do not support unthreaded Perls on OpenBSD.  Or just flush OpenBSD down the toilet, it is a pretty terrible platform to work on.

Have not tested:

  - any big endian platforms.  This was a tricky thing with `FFI::Raw`, though I *think* `FFI::Platypus` shouldn't have as many problems since we are using unions instead of casts.  At some point I will get my old Power Mac out, to see if I can test on that.
  - anything else like AIX, HP-UX, android, etc.
  - ARM - should see if I can test on a raspberry pi
  - OpenVMS, not supported as far as I know by libffi

Ported `UUID::FFI` to use platypus.  It is much less verbose, and probably faster than the `FFI::Raw` version.

Overall it is pretty close to what will eventually go to CPAN.

**Comment by plicease** [comment]
Something not quite right about closures that was not revealed in any of my unit tests.  Ran into this while porting `FFI::TinyCC`.  Good news is that I managed the port, the bad news I am in for some debugging with ref counts and closures.  #4 is thus still the key to things.  Everything else is optional nice to have later status.

Documentation coverage is almost complete.  The custom type section of Type.pod needs to be done.  I'd like to make a stab at a custom type API (this sort of sums up #15, #10 and #11), and then finish up Type.pod.  In a pinch the API can be delayed, but it will probably mean writing and then re-writing the custom types documentation.

New version I am calling this a beta:

https://dist.wdlabs.com/FFI-Platypus-0.07.tar.gz

**Comment by mohawk2** [comment]
May I humbly suggest releasing to CPAN with version something like 0.07_01, with the right metadata featuring this repo, and probably the bugtracker pointing at the GH issues, to help bring in others? That acts as kind of an invitation for PRs and other collaborators.

**Comment by plicease** [comment]
@mohawk2 I appreciate the encouragement, but I wanted to flesh out the custom types API a little.  It's not bad now, but it will need some work (#18,#17, sort of related: #11).  I've marked the API as experimental, so I do not consider them blockers, though they are important.  This version is pretty close to what I will release to CPAN shortly:

https://dist.wdlabs.com/FFI-Platypus-0.10.tar.gz

I just want to do a little more odd platform testing and write some documentation for custom types, which I think is the only hole in the documentation coverage.

**Comment by plicease** [comment]
On its way to CPAN as 0.12.

**Comment by mohawk2** [comment]
Nice!
